---
title: "Continente"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---



<i class="fas fa-globe"></i> Continente 
===================================== 

Row
-----------------------------------------------------------------------

### Total de Importaciones en Medicamentos en el año 2020 US$

```{r}
valueBox(format(round(as.numeric(cantidad_dinero), 1), big.mark=","), icon = "fa-coins")
```

### Total de unidades importadas en Medicamentos en el año 2020

```{r}
valueBox(format(round(as.numeric(Cantidad_unidades), 1), big.mark=","), icon = "fa-warehouse")
```

### Cantidad Paises importadores en el año 2020

```{r}
valueBox(Cantidad_pais, icon = "fa-globe-americas")
```

Row
-----------------------------------------------------------------------

### **Mapa mundial de paises que importan medicamentos a Guatemala del 2016 - 2020**
```{r}

world_map <- map_data("world")

medicamentos %>% 
  filter(tipo == 2) %>% 
  group_by(pais, iso3c) %>% 
  select(pais,monto, iso3c) %>% 
  summarise(total = sum(monto)) %>%  
  plot_geo(locationmode = 'ISO-3') %>%
  add_trace(z = ~total, locations = ~iso3c) %>%
  layout(geo = list(scope = 'world')) %>%
  colorbar(title = "Importaciones de medicamentos ($)")

```


### **Cantidad total de importaciones por continente del 2016 - 2020 **
```{r}

g16 <-importaciones %>% 
      filter(tipo == 2, anio == 2016) %>% 
      group_by(anio, continente) %>% 
      select(anio, continente,monto) %>%
      summarise(total = sum(monto)) %>% 
      ggplot(aes(x=reorder(continente,total), y=total)) + 
      scale_y_continuous(labels = label_number(suffix = "M", scale = 1e-6),  limits = c(0, 250000000),breaks = seq(0,300000000, 50000000)) +
      geom_bar( stat='identity', color = "#0D335D", fill = "#0D335D") +
      labs(x = NULL,
           y = "2016") +
      theme_minimal()+
      coord_flip()

g17 <-importaciones %>% 
      filter(tipo == 2, anio == 2017) %>% 
      group_by(anio, continente) %>% 
      select(anio, continente,monto) %>%
      summarise(total = sum(monto)) %>% 
      ggplot(aes(x=reorder(continente,total), y=total)) + 
      scale_y_continuous(labels = label_number(suffix = "M", scale = 1e-6),  limits = c(0, 250000000),breaks = seq(0,300000000, 50000000)) +
      geom_bar( stat='identity', color = "#0D335D", fill = "#0D335D") +
      labs(x = NULL,
           y = "2017") +
      theme_minimal()+
      coord_flip()


g18 <-importaciones %>% 
      filter(tipo == 2, anio == 2018) %>% 
      group_by(anio, continente) %>% 
      select(anio, continente,monto) %>%
      summarise(total = sum(monto)) %>% 
      ggplot(aes(x=reorder(continente,total), y=total)) + 
      scale_y_continuous(labels = label_number(suffix = "M", scale = 1e-6),  limits = c(0, 250000000),breaks = seq(0,300000000, 50000000)) +
      geom_bar( stat='identity', color = "#0D335D", fill = "#0D335D") +
      labs(x = NULL,
           y = "2018") +
      theme_minimal()+
      coord_flip()


g19 <-importaciones %>% 
      filter(tipo == 2, anio == 2019) %>% 
      group_by(anio, continente) %>% 
      select(anio, continente,monto) %>%
      summarise(total = sum(monto)) %>% 
      ggplot(aes(x=reorder(continente,total), y=total)) + 
      scale_y_continuous(labels = label_number(suffix = "M", scale = 1e-6),  limits = c(0, 250000000),breaks = seq(0,300000000, 50000000)) +
      geom_bar( stat='identity', color = "#0D335D", fill = "#0D335D") +
      labs(x = NULL,
           y = "2019") +
      theme_minimal()+
      coord_flip()


g20 <-importaciones %>% 
      filter(tipo == 2, anio == 2020) %>% 
      group_by(anio, continente) %>% 
      select(anio, continente,monto) %>%
      summarise(total = sum(monto)) %>%
      ggplot(aes(x=reorder(continente,total), y=total)) + 
      scale_y_continuous(labels = label_number(suffix = "M", scale = 1e-6),  limits = c(0, 250000000),breaks = seq(0,300000000, 50000000)) +
      geom_bar( stat='identity', color = "#0D335D", fill = "#0D335D") +
      labs(x = NULL,
           y = "2020") +
      theme_minimal()+
      coord_flip()

figure <- ggarrange(g16, g17,g18, g19,g20,ncol = 2, nrow = 3)
figure

```

